#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_NRF_RPC=y
CONFIG_NRF_RPC_CBOR=y
CONFIG_NRF_RPC_ZCBOR_BACKUPS=1
CONFIG_NRF_RPC_THREAD_STACK_SIZE=4096
CONFIG_NRF_RPC_GROUP_INIT_WAIT_TIME=-1
CONFIG_NRF_RPC_UART_TRANSPORT=y

CONFIG_UART_LINE_CTRL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_FUNC_NAME_PREFIX_DBG=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_SHELL_LOG_BACKEND=y


#########################################3
CONFIG_POLL=y
CONFIG_GPIO=y
CONFIG_USE_SEGGER_RTT=n

CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_BOOT_BANNER=n
# malloc used by test_common/test_events.c and tca_transports/uart_zephyr_async.c
CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE=512
# allows Ozone and GDB to monitor active threads
CONFIG_DEBUG_THREAD_INFO=y
# dont restart the board when fatal error occurs
CONFIG_RESET_ON_FATAL_ERROR=n
# enable zephyr logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
# needed for custom log backend when NCS > v2.0.2
CONFIG_LOG_OUTPUT=y
# use TCA log backend
CONFIG_TCA_LOG_BACKEND=y
# thread stack guard (not supported on Cortex-M4)
CONFIG_BUILTIN_STACK_GUARD=y

CONFIG_TCA_MAX_PACKET_PAYLOAD_SIZE=8200

# CONFIG_TCA_TRANSPORT_UART_ZEPHYR=y
CONFIG_TCA_TRANSPORT_RTT=y
